-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 15:32:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `phone` INT NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shopping_date` DATE NOT NULL,
  `total_amount` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  CONSTRAINT `fk_ShoppingCart_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ShoppingCart_User_idx` ON `mydb`.`ShoppingCart` (`User_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCartProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCartProduct` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `description` TEXT(100) NOT NULL,
  `Provider_id` INT NOT NULL,
  `Category_id` INT NOT NULL,
  `Brand_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Provider_id`, `Category_id`, `Brand_id`),
  CONSTRAINT `fk_Product_Provider1`
    FOREIGN KEY (`Provider_id`)
    REFERENCES `mydb`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `mydb`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Brand1`
    FOREIGN KEY (`Brand_id`)
    REFERENCES `mydb`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Product_Provider1_idx` ON `mydb`.`Product` (`Provider_id` ASC) VISIBLE;

CREATE INDEX `fk_Product_Category1_idx` ON `mydb`.`Product` (`Category_id` ASC) VISIBLE;

CREATE INDEX `fk_Product_Brand1_idx` ON `mydb`.`Product` (`Brand_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCartProducts_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCartProducts_has_Product` (
  `ShoppingCartProducts_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`ShoppingCartProducts_id`, `Product_id`),
  CONSTRAINT `fk_ShoppingCartProducts_has_Product_ShoppingCartProducts1`
    FOREIGN KEY (`ShoppingCartProducts_id`)
    REFERENCES `mydb`.`ShoppingCartProduct` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCartProducts_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `mydb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ShoppingCartProducts_has_Product_Product1_idx` ON `mydb`.`ShoppingCartProducts_has_Product` (`Product_id` ASC) VISIBLE;

CREATE INDEX `fk_ShoppingCartProducts_has_Product_ShoppingCartProducts1_idx` ON `mydb`.`ShoppingCartProducts_has_Product` (`ShoppingCartProducts_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart_has_ShoppingCartProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart_has_ShoppingCartProduct` (
  `ShoppingCart_id` INT NOT NULL,
  `ShoppingCart_User_id` INT NOT NULL,
  `ShoppingCartProduct_id` INT NOT NULL,
  PRIMARY KEY (`ShoppingCart_id`, `ShoppingCart_User_id`, `ShoppingCartProduct_id`),
  CONSTRAINT `fk_ShoppingCart_has_ShoppingCartProduct_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_id` , `ShoppingCart_User_id`)
    REFERENCES `mydb`.`ShoppingCart` (`id` , `User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCart_has_ShoppingCartProduct_ShoppingCartProduct1`
    FOREIGN KEY (`ShoppingCartProduct_id`)
    REFERENCES `mydb`.`ShoppingCartProduct` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ShoppingCart_has_ShoppingCartProduct_ShoppingCartProduct_idx` ON `mydb`.`ShoppingCart_has_ShoppingCartProduct` (`ShoppingCartProduct_id` ASC) VISIBLE;

CREATE INDEX `fk_ShoppingCart_has_ShoppingCartProduct_ShoppingCart1_idx` ON `mydb`.`ShoppingCart_has_ShoppingCartProduct` (`ShoppingCart_id` ASC, `ShoppingCart_User_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
