-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 21:11:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `email` VARCHAR(25) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarritoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CarritoCompra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaCompra` DATE NOT NULL,
  `montoCompra` INT NOT NULL,
  `Usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Usuarios_id`),
  CONSTRAINT `fk_CarritoCompra_Usuarios`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `mydb`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CarritoCompra_Usuarios_idx` ON `mydb`.`CarritoCompra` (`Usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ProductosCarritoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductosCarritoCompra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CarritoCompra_has_ProductosCarritoCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CarritoCompra_has_ProductosCarritoCompra` (
  `CarritoCompra_id` INT NOT NULL,
  `CarritoCompra_Usuarios_id` INT NOT NULL,
  `ProductosCarritoCompra_id` INT NOT NULL,
  PRIMARY KEY (`CarritoCompra_id`, `CarritoCompra_Usuarios_id`, `ProductosCarritoCompra_id`),
  CONSTRAINT `fk_CarritoCompra_has_ProductosCarritoCompra_CarritoCompra1`
    FOREIGN KEY (`CarritoCompra_id` , `CarritoCompra_Usuarios_id`)
    REFERENCES `mydb`.`CarritoCompra` (`id` , `Usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarritoCompra_has_ProductosCarritoCompra_ProductosCarritoC1`
    FOREIGN KEY (`ProductosCarritoCompra_id`)
    REFERENCES `mydb`.`ProductosCarritoCompra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CarritoCompra_has_ProductosCarritoCompra_ProductosCarrit_idx` ON `mydb`.`CarritoCompra_has_ProductosCarritoCompra` (`ProductosCarritoCompra_id` ASC) VISIBLE;

CREATE INDEX `fk_CarritoCompra_has_ProductosCarritoCompra_CarritoCompra1_idx` ON `mydb`.`CarritoCompra_has_ProductosCarritoCompra` (`CarritoCompra_id` ASC, `CarritoCompra_Usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `precio` INT NOT NULL,
  `descripcion` TEXT(100) NOT NULL,
  `Categoria_id` INT NOT NULL,
  `Marca_id` INT NOT NULL,
  `Proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Categoria_id`, `Marca_id`, `Proveedor_id`),
  CONSTRAINT `fk_Productos_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `mydb`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `mydb`.`Marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Proveedor1`
    FOREIGN KEY (`Proveedor_id`)
    REFERENCES `mydb`.`Proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_Categoria1_idx` ON `mydb`.`Productos` (`Categoria_id` ASC) VISIBLE;

CREATE INDEX `fk_Productos_Marca1_idx` ON `mydb`.`Productos` (`Marca_id` ASC) VISIBLE;

CREATE INDEX `fk_Productos_Proveedor1_idx` ON `mydb`.`Productos` (`Proveedor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ProductosCarritoCompra_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductosCarritoCompra_has_Productos` (
  `ProductosCarritoCompra_id` INT NOT NULL,
  `Productos_id` INT NOT NULL,
  PRIMARY KEY (`ProductosCarritoCompra_id`, `Productos_id`),
  CONSTRAINT `fk_ProductosCarritoCompra_has_Productos_ProductosCarritoCompra1`
    FOREIGN KEY (`ProductosCarritoCompra_id`)
    REFERENCES `mydb`.`ProductosCarritoCompra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosCarritoCompra_has_Productos_Productos1`
    FOREIGN KEY (`Productos_id`)
    REFERENCES `mydb`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ProductosCarritoCompra_has_Productos_Productos1_idx` ON `mydb`.`ProductosCarritoCompra_has_Productos` (`Productos_id` ASC) VISIBLE;

CREATE INDEX `fk_ProductosCarritoCompra_has_Productos_ProductosCarritoCom_idx` ON `mydb`.`ProductosCarritoCompra_has_Productos` (`ProductosCarritoCompra_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CaracteristicasProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CaracteristicasProducto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Productos_id` INT NOT NULL,
  `Productos_Categoria_id` INT NOT NULL,
  `Productos_Marca_id` INT NOT NULL,
  `Productos_Proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Productos_id`, `Productos_Categoria_id`, `Productos_Marca_id`, `Productos_Proveedor_id`),
  CONSTRAINT `fk_CaracteristicasProducto_Productos1`
    FOREIGN KEY (`Productos_id` , `Productos_Categoria_id` , `Productos_Marca_id` , `Productos_Proveedor_id`)
    REFERENCES `mydb`.`Productos` (`id` , `Categoria_id` , `Marca_id` , `Proveedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CaracteristicasProducto_Productos1_idx` ON `mydb`.`CaracteristicasProducto` (`Productos_id` ASC, `Productos_Categoria_id` ASC, `Productos_Marca_id` ASC, `Productos_Proveedor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caracteristica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CaracteristicasProducto_has_Caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CaracteristicasProducto_has_Caracteristica` (
  `CaracteristicasProducto_id` INT NOT NULL,
  `Caracteristica_id` INT NOT NULL,
  PRIMARY KEY (`CaracteristicasProducto_id`, `Caracteristica_id`),
  CONSTRAINT `fk_CaracteristicasProducto_has_Caracteristica_Caracteristicas1`
    FOREIGN KEY (`CaracteristicasProducto_id`)
    REFERENCES `mydb`.`CaracteristicasProducto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CaracteristicasProducto_has_Caracteristica_Caracteristica1`
    FOREIGN KEY (`Caracteristica_id`)
    REFERENCES `mydb`.`Caracteristica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CaracteristicasProducto_has_Caracteristica_Caracteristic_idx` ON `mydb`.`CaracteristicasProducto_has_Caracteristica` (`Caracteristica_id` ASC) VISIBLE;

CREATE INDEX `fk_CaracteristicasProducto_has_Caracteristica_Caracteristic_idx1` ON `mydb`.`CaracteristicasProducto_has_Caracteristica` (`CaracteristicasProducto_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
